import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='p-10 mx-auto mb-10 text-center'>
      <Head>
        <title>Geissele</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1 className='p-10 mx-auto mb-10 text-center'>
          Welcome to My Geissele!
        </h1>
      </header>

      <main className='p-10 mx-auto mb-10 text-center'>
        A Site to Learn About My Geissle Automatics and the URGI Rifle
        {/* <div className='p-10 mx-auto mb-10 text-center'> */}
        <li ><img src='/URGI-profile.jpg' alt='URGI Rifle with sling' /></li>
        {/* <Image src='/logo-g.png' alt='URGI Rifle with sling' width={72} height={16} /> */}
        {/* <a href="https://nextjs.org/docs" className='p-10 mx-auto mb-10 text-center'>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className='p-10 mx-auto mb-10 text-center'>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className='p-10 mx-auto mb-10 text-center'
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className='p-10 mx-auto mb-10 text-center'
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}

      </main >

      <footer className='p-10 mx-auto mb-10 text-center'>
        <p>&copy;Kevin Henry MMXXI</p>
      </footer>
    </div >
  )
}
